[package]
name = "nviq-stardict"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
_ffi_util = { path = "../_ffi_util" }
rust-stardict = { git = "https://github.com/AnthonyK213/rust-stardict" }
serde_json = "1.0.145"
